name: Trigger community site update

on:
  push:
  pull_request:
  create:

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger community site update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: voiceflow-community/voiceflow-community.github.io
          event-type: repo-created-or-updated
